
/*
Auto-generated by CVXPYgen on July 19, 2025 at 17:32:05.
Content: Function definitions.
*/

#include "cpg_solve.h"
#include "cpg_workspace.h"

static cpg_int i;
static cpg_int j;

// Update user-defined parameters
void cpg_update_w_tr(cpg_float val){
  cpg_params_vec[0] = val;
  Canon_Outdated.P = 1;
}

void cpg_update_f_dt_last(cpg_float val){
  cpg_params_vec[1] = val;
  Canon_Outdated.d = 1;
}

void cpg_update_gf_dt_last(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2] = val;
  Canon_Outdated.c = 1;
}

void cpg_update_f_ct_last(cpg_float val){
  cpg_params_vec[158] = val;
  Canon_Outdated.d = 1;
}

void cpg_update_A_ct_last(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+159] = val;
  Canon_Outdated.c = 1;
}

void cpg_update_B_ct_last(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+302] = val;
  Canon_Outdated.c = 1;
}

void cpg_update_C_ct_last(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+346] = val;
  Canon_Outdated.c = 1;
}

void cpg_update_S_ct_last(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+390] = val;
  Canon_Outdated.c = 1;
}

void cpg_update_X_last(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+401] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_f_bar(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+557] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_A_bar(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+700] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_B_bar(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2559] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_C_bar(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+3131] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_S_bar(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+3703] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_U_last(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+3846] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_S_last(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+3894] = val;
  Canon_Outdated.b = 1;
}

// Map user-defined to canonical parameters
void cpg_canonicalize_P(){
  for(i=0; i<25; i++){
    Canon_Params.P->x[i] = 0;
    for(j=canon_P_map.p[i]; j<canon_P_map.p[i+1]; j++){
      Canon_Params.P->x[i] += canon_P_map.x[j]*cpg_params_vec[canon_P_map.i[j]];
    }
  }
}

void cpg_canonicalize_c(){
  for(i=0; i<788; i++){
    Canon_Params.c[i] = 0;
    for(j=canon_c_map.p[i]; j<canon_c_map.p[i+1]; j++){
      Canon_Params.c[i] += canon_c_map.x[j]*cpg_params_vec[canon_c_map.i[j]];
    }
  }
}

void cpg_canonicalize_d(){
  for(i=0; i<1; i++){
    Canon_Params.d = 0;
    for(j=canon_d_map.p[i]; j<canon_d_map.p[i+1]; j++){
      Canon_Params.d += canon_d_map.x[j]*cpg_params_vec[canon_d_map.i[j]];
    }
  }
}

void cpg_canonicalize_A(){
  for(i=0; i<3893; i++){
    Canon_Params.A->x[i] = 0;
    for(j=canon_A_map.p[i]; j<canon_A_map.p[i+1]; j++){
      Canon_Params.A->x[i] += canon_A_map.x[j]*cpg_params_vec[canon_A_map.i[j]];
    }
  }
}

void cpg_canonicalize_b(){
  for(i=0; i<389; i++){
    Canon_Params.b[i] = 0;
    for(j=canon_b_map.p[i]; j<canon_b_map.p[i+1]; j++){
      Canon_Params.b[i] += canon_b_map.x[j]*cpg_params_vec[canon_b_map.i[j]];
    }
  }
}

// Retrieve primal solution in terms of user-defined variables
void cpg_retrieve_prim(){
  CPG_Prim.dx[0] = qoco_solver->sol->x[168];
  CPG_Prim.dx[1] = qoco_solver->sol->x[169];
  CPG_Prim.dx[2] = qoco_solver->sol->x[170];
  CPG_Prim.dx[3] = qoco_solver->sol->x[171];
  CPG_Prim.dx[4] = qoco_solver->sol->x[172];
  CPG_Prim.dx[5] = qoco_solver->sol->x[173];
  CPG_Prim.dx[6] = qoco_solver->sol->x[174];
  CPG_Prim.dx[7] = qoco_solver->sol->x[175];
  CPG_Prim.dx[8] = qoco_solver->sol->x[176];
  CPG_Prim.dx[9] = qoco_solver->sol->x[177];
  CPG_Prim.dx[10] = qoco_solver->sol->x[178];
  CPG_Prim.dx[11] = qoco_solver->sol->x[179];
  CPG_Prim.dx[12] = qoco_solver->sol->x[180];
  CPG_Prim.dx[13] = qoco_solver->sol->x[181];
  CPG_Prim.dx[14] = qoco_solver->sol->x[182];
  CPG_Prim.dx[15] = qoco_solver->sol->x[183];
  CPG_Prim.dx[16] = qoco_solver->sol->x[184];
  CPG_Prim.dx[17] = qoco_solver->sol->x[185];
  CPG_Prim.dx[18] = qoco_solver->sol->x[186];
  CPG_Prim.dx[19] = qoco_solver->sol->x[187];
  CPG_Prim.dx[20] = qoco_solver->sol->x[188];
  CPG_Prim.dx[21] = qoco_solver->sol->x[189];
  CPG_Prim.dx[22] = qoco_solver->sol->x[190];
  CPG_Prim.dx[23] = qoco_solver->sol->x[191];
  CPG_Prim.dx[24] = qoco_solver->sol->x[192];
  CPG_Prim.dx[25] = qoco_solver->sol->x[193];
  CPG_Prim.dx[26] = qoco_solver->sol->x[194];
  CPG_Prim.dx[27] = qoco_solver->sol->x[195];
  CPG_Prim.dx[28] = qoco_solver->sol->x[196];
  CPG_Prim.dx[29] = qoco_solver->sol->x[197];
  CPG_Prim.dx[30] = qoco_solver->sol->x[198];
  CPG_Prim.dx[31] = qoco_solver->sol->x[199];
  CPG_Prim.dx[32] = qoco_solver->sol->x[200];
  CPG_Prim.dx[33] = qoco_solver->sol->x[201];
  CPG_Prim.dx[34] = qoco_solver->sol->x[202];
  CPG_Prim.dx[35] = qoco_solver->sol->x[203];
  CPG_Prim.dx[36] = qoco_solver->sol->x[204];
  CPG_Prim.dx[37] = qoco_solver->sol->x[205];
  CPG_Prim.dx[38] = qoco_solver->sol->x[206];
  CPG_Prim.dx[39] = qoco_solver->sol->x[207];
  CPG_Prim.dx[40] = qoco_solver->sol->x[208];
  CPG_Prim.dx[41] = qoco_solver->sol->x[209];
  CPG_Prim.dx[42] = qoco_solver->sol->x[210];
  CPG_Prim.dx[43] = qoco_solver->sol->x[211];
  CPG_Prim.dx[44] = qoco_solver->sol->x[212];
  CPG_Prim.dx[45] = qoco_solver->sol->x[213];
  CPG_Prim.dx[46] = qoco_solver->sol->x[214];
  CPG_Prim.dx[47] = qoco_solver->sol->x[215];
  CPG_Prim.dx[48] = qoco_solver->sol->x[216];
  CPG_Prim.dx[49] = qoco_solver->sol->x[217];
  CPG_Prim.dx[50] = qoco_solver->sol->x[218];
  CPG_Prim.dx[51] = qoco_solver->sol->x[219];
  CPG_Prim.dx[52] = qoco_solver->sol->x[220];
  CPG_Prim.dx[53] = qoco_solver->sol->x[221];
  CPG_Prim.dx[54] = qoco_solver->sol->x[222];
  CPG_Prim.dx[55] = qoco_solver->sol->x[223];
  CPG_Prim.dx[56] = qoco_solver->sol->x[224];
  CPG_Prim.dx[57] = qoco_solver->sol->x[225];
  CPG_Prim.dx[58] = qoco_solver->sol->x[226];
  CPG_Prim.dx[59] = qoco_solver->sol->x[227];
  CPG_Prim.dx[60] = qoco_solver->sol->x[228];
  CPG_Prim.dx[61] = qoco_solver->sol->x[229];
  CPG_Prim.dx[62] = qoco_solver->sol->x[230];
  CPG_Prim.dx[63] = qoco_solver->sol->x[231];
  CPG_Prim.dx[64] = qoco_solver->sol->x[232];
  CPG_Prim.dx[65] = qoco_solver->sol->x[233];
  CPG_Prim.dx[66] = qoco_solver->sol->x[234];
  CPG_Prim.dx[67] = qoco_solver->sol->x[235];
  CPG_Prim.dx[68] = qoco_solver->sol->x[236];
  CPG_Prim.dx[69] = qoco_solver->sol->x[237];
  CPG_Prim.dx[70] = qoco_solver->sol->x[238];
  CPG_Prim.dx[71] = qoco_solver->sol->x[239];
  CPG_Prim.dx[72] = qoco_solver->sol->x[240];
  CPG_Prim.dx[73] = qoco_solver->sol->x[241];
  CPG_Prim.dx[74] = qoco_solver->sol->x[242];
  CPG_Prim.dx[75] = qoco_solver->sol->x[243];
  CPG_Prim.dx[76] = qoco_solver->sol->x[244];
  CPG_Prim.dx[77] = qoco_solver->sol->x[245];
  CPG_Prim.dx[78] = qoco_solver->sol->x[246];
  CPG_Prim.dx[79] = qoco_solver->sol->x[247];
  CPG_Prim.dx[80] = qoco_solver->sol->x[248];
  CPG_Prim.dx[81] = qoco_solver->sol->x[249];
  CPG_Prim.dx[82] = qoco_solver->sol->x[250];
  CPG_Prim.dx[83] = qoco_solver->sol->x[251];
  CPG_Prim.dx[84] = qoco_solver->sol->x[252];
  CPG_Prim.dx[85] = qoco_solver->sol->x[253];
  CPG_Prim.dx[86] = qoco_solver->sol->x[254];
  CPG_Prim.dx[87] = qoco_solver->sol->x[255];
  CPG_Prim.dx[88] = qoco_solver->sol->x[256];
  CPG_Prim.dx[89] = qoco_solver->sol->x[257];
  CPG_Prim.dx[90] = qoco_solver->sol->x[258];
  CPG_Prim.dx[91] = qoco_solver->sol->x[259];
  CPG_Prim.dx[92] = qoco_solver->sol->x[260];
  CPG_Prim.dx[93] = qoco_solver->sol->x[261];
  CPG_Prim.dx[94] = qoco_solver->sol->x[262];
  CPG_Prim.dx[95] = qoco_solver->sol->x[263];
  CPG_Prim.dx[96] = qoco_solver->sol->x[264];
  CPG_Prim.dx[97] = qoco_solver->sol->x[265];
  CPG_Prim.dx[98] = qoco_solver->sol->x[266];
  CPG_Prim.dx[99] = qoco_solver->sol->x[267];
  CPG_Prim.dx[100] = qoco_solver->sol->x[268];
  CPG_Prim.dx[101] = qoco_solver->sol->x[269];
  CPG_Prim.dx[102] = qoco_solver->sol->x[270];
  CPG_Prim.dx[103] = qoco_solver->sol->x[271];
  CPG_Prim.dx[104] = qoco_solver->sol->x[272];
  CPG_Prim.dx[105] = qoco_solver->sol->x[273];
  CPG_Prim.dx[106] = qoco_solver->sol->x[274];
  CPG_Prim.dx[107] = qoco_solver->sol->x[275];
  CPG_Prim.dx[108] = qoco_solver->sol->x[276];
  CPG_Prim.dx[109] = qoco_solver->sol->x[277];
  CPG_Prim.dx[110] = qoco_solver->sol->x[278];
  CPG_Prim.dx[111] = qoco_solver->sol->x[279];
  CPG_Prim.dx[112] = qoco_solver->sol->x[280];
  CPG_Prim.dx[113] = qoco_solver->sol->x[281];
  CPG_Prim.dx[114] = qoco_solver->sol->x[282];
  CPG_Prim.dx[115] = qoco_solver->sol->x[283];
  CPG_Prim.dx[116] = qoco_solver->sol->x[284];
  CPG_Prim.dx[117] = qoco_solver->sol->x[285];
  CPG_Prim.dx[118] = qoco_solver->sol->x[286];
  CPG_Prim.dx[119] = qoco_solver->sol->x[287];
  CPG_Prim.dx[120] = qoco_solver->sol->x[288];
  CPG_Prim.dx[121] = qoco_solver->sol->x[289];
  CPG_Prim.dx[122] = qoco_solver->sol->x[290];
  CPG_Prim.dx[123] = qoco_solver->sol->x[291];
  CPG_Prim.dx[124] = qoco_solver->sol->x[292];
  CPG_Prim.dx[125] = qoco_solver->sol->x[293];
  CPG_Prim.dx[126] = qoco_solver->sol->x[294];
  CPG_Prim.dx[127] = qoco_solver->sol->x[295];
  CPG_Prim.dx[128] = qoco_solver->sol->x[296];
  CPG_Prim.dx[129] = qoco_solver->sol->x[297];
  CPG_Prim.dx[130] = qoco_solver->sol->x[298];
  CPG_Prim.dx[131] = qoco_solver->sol->x[299];
  CPG_Prim.dx[132] = qoco_solver->sol->x[300];
  CPG_Prim.dx[133] = qoco_solver->sol->x[301];
  CPG_Prim.dx[134] = qoco_solver->sol->x[302];
  CPG_Prim.dx[135] = qoco_solver->sol->x[303];
  CPG_Prim.dx[136] = qoco_solver->sol->x[304];
  CPG_Prim.dx[137] = qoco_solver->sol->x[305];
  CPG_Prim.dx[138] = qoco_solver->sol->x[306];
  CPG_Prim.dx[139] = qoco_solver->sol->x[307];
  CPG_Prim.dx[140] = qoco_solver->sol->x[308];
  CPG_Prim.dx[141] = qoco_solver->sol->x[309];
  CPG_Prim.dx[142] = qoco_solver->sol->x[310];
  CPG_Prim.dx[143] = qoco_solver->sol->x[311];
  CPG_Prim.dx[144] = qoco_solver->sol->x[312];
  CPG_Prim.dx[145] = qoco_solver->sol->x[313];
  CPG_Prim.dx[146] = qoco_solver->sol->x[314];
  CPG_Prim.dx[147] = qoco_solver->sol->x[315];
  CPG_Prim.dx[148] = qoco_solver->sol->x[316];
  CPG_Prim.dx[149] = qoco_solver->sol->x[317];
  CPG_Prim.dx[150] = qoco_solver->sol->x[318];
  CPG_Prim.dx[151] = qoco_solver->sol->x[319];
  CPG_Prim.dx[152] = qoco_solver->sol->x[320];
  CPG_Prim.dx[153] = qoco_solver->sol->x[321];
  CPG_Prim.dx[154] = qoco_solver->sol->x[322];
  CPG_Prim.dx[155] = qoco_solver->sol->x[323];
  CPG_Prim.du[0] = qoco_solver->sol->x[324];
  CPG_Prim.du[1] = qoco_solver->sol->x[325];
  CPG_Prim.du[2] = qoco_solver->sol->x[326];
  CPG_Prim.du[3] = qoco_solver->sol->x[327];
  CPG_Prim.du[4] = qoco_solver->sol->x[328];
  CPG_Prim.du[5] = qoco_solver->sol->x[329];
  CPG_Prim.du[6] = qoco_solver->sol->x[330];
  CPG_Prim.du[7] = qoco_solver->sol->x[331];
  CPG_Prim.du[8] = qoco_solver->sol->x[332];
  CPG_Prim.du[9] = qoco_solver->sol->x[333];
  CPG_Prim.du[10] = qoco_solver->sol->x[334];
  CPG_Prim.du[11] = qoco_solver->sol->x[335];
  CPG_Prim.du[12] = qoco_solver->sol->x[336];
  CPG_Prim.du[13] = qoco_solver->sol->x[337];
  CPG_Prim.du[14] = qoco_solver->sol->x[338];
  CPG_Prim.du[15] = qoco_solver->sol->x[339];
  CPG_Prim.du[16] = qoco_solver->sol->x[340];
  CPG_Prim.du[17] = qoco_solver->sol->x[341];
  CPG_Prim.du[18] = qoco_solver->sol->x[342];
  CPG_Prim.du[19] = qoco_solver->sol->x[343];
  CPG_Prim.du[20] = qoco_solver->sol->x[344];
  CPG_Prim.du[21] = qoco_solver->sol->x[345];
  CPG_Prim.du[22] = qoco_solver->sol->x[346];
  CPG_Prim.du[23] = qoco_solver->sol->x[347];
  CPG_Prim.du[24] = qoco_solver->sol->x[348];
  CPG_Prim.du[25] = qoco_solver->sol->x[349];
  CPG_Prim.du[26] = qoco_solver->sol->x[350];
  CPG_Prim.du[27] = qoco_solver->sol->x[351];
  CPG_Prim.du[28] = qoco_solver->sol->x[352];
  CPG_Prim.du[29] = qoco_solver->sol->x[353];
  CPG_Prim.du[30] = qoco_solver->sol->x[354];
  CPG_Prim.du[31] = qoco_solver->sol->x[355];
  CPG_Prim.du[32] = qoco_solver->sol->x[356];
  CPG_Prim.du[33] = qoco_solver->sol->x[357];
  CPG_Prim.du[34] = qoco_solver->sol->x[358];
  CPG_Prim.du[35] = qoco_solver->sol->x[359];
  CPG_Prim.du[36] = qoco_solver->sol->x[360];
  CPG_Prim.du[37] = qoco_solver->sol->x[361];
  CPG_Prim.du[38] = qoco_solver->sol->x[362];
  CPG_Prim.du[39] = qoco_solver->sol->x[363];
  CPG_Prim.du[40] = qoco_solver->sol->x[364];
  CPG_Prim.du[41] = qoco_solver->sol->x[365];
  CPG_Prim.du[42] = qoco_solver->sol->x[366];
  CPG_Prim.du[43] = qoco_solver->sol->x[367];
  CPG_Prim.du[44] = qoco_solver->sol->x[368];
  CPG_Prim.du[45] = qoco_solver->sol->x[369];
  CPG_Prim.du[46] = qoco_solver->sol->x[370];
  CPG_Prim.du[47] = qoco_solver->sol->x[371];
  CPG_Prim.ds[0] = qoco_solver->sol->x[372];
  CPG_Prim.ds[1] = qoco_solver->sol->x[373];
  CPG_Prim.ds[2] = qoco_solver->sol->x[374];
  CPG_Prim.ds[3] = qoco_solver->sol->x[375];
  CPG_Prim.ds[4] = qoco_solver->sol->x[376];
  CPG_Prim.ds[5] = qoco_solver->sol->x[377];
  CPG_Prim.ds[6] = qoco_solver->sol->x[378];
  CPG_Prim.ds[7] = qoco_solver->sol->x[379];
  CPG_Prim.ds[8] = qoco_solver->sol->x[380];
  CPG_Prim.ds[9] = qoco_solver->sol->x[381];
  CPG_Prim.ds[10] = qoco_solver->sol->x[382];
  CPG_Prim.nu[0] = qoco_solver->sol->x[405];
  CPG_Prim.nu[1] = qoco_solver->sol->x[406];
  CPG_Prim.nu[2] = qoco_solver->sol->x[407];
  CPG_Prim.nu[3] = qoco_solver->sol->x[408];
  CPG_Prim.nu[4] = qoco_solver->sol->x[409];
  CPG_Prim.nu[5] = qoco_solver->sol->x[410];
  CPG_Prim.nu[6] = qoco_solver->sol->x[411];
  CPG_Prim.nu[7] = qoco_solver->sol->x[412];
  CPG_Prim.nu[8] = qoco_solver->sol->x[413];
  CPG_Prim.nu[9] = qoco_solver->sol->x[414];
  CPG_Prim.nu[10] = qoco_solver->sol->x[415];
  CPG_Prim.nu[11] = qoco_solver->sol->x[416];
  CPG_Prim.nu[12] = qoco_solver->sol->x[417];
  CPG_Prim.nu[13] = qoco_solver->sol->x[418];
  CPG_Prim.nu[14] = qoco_solver->sol->x[419];
  CPG_Prim.nu[15] = qoco_solver->sol->x[420];
  CPG_Prim.nu[16] = qoco_solver->sol->x[421];
  CPG_Prim.nu[17] = qoco_solver->sol->x[422];
  CPG_Prim.nu[18] = qoco_solver->sol->x[423];
  CPG_Prim.nu[19] = qoco_solver->sol->x[424];
  CPG_Prim.nu[20] = qoco_solver->sol->x[425];
  CPG_Prim.nu[21] = qoco_solver->sol->x[426];
  CPG_Prim.nu[22] = qoco_solver->sol->x[427];
  CPG_Prim.nu[23] = qoco_solver->sol->x[428];
  CPG_Prim.nu[24] = qoco_solver->sol->x[429];
  CPG_Prim.nu[25] = qoco_solver->sol->x[430];
  CPG_Prim.nu[26] = qoco_solver->sol->x[431];
  CPG_Prim.nu[27] = qoco_solver->sol->x[432];
  CPG_Prim.nu[28] = qoco_solver->sol->x[433];
  CPG_Prim.nu[29] = qoco_solver->sol->x[434];
  CPG_Prim.nu[30] = qoco_solver->sol->x[435];
  CPG_Prim.nu[31] = qoco_solver->sol->x[436];
  CPG_Prim.nu[32] = qoco_solver->sol->x[437];
  CPG_Prim.nu[33] = qoco_solver->sol->x[438];
  CPG_Prim.nu[34] = qoco_solver->sol->x[439];
  CPG_Prim.nu[35] = qoco_solver->sol->x[440];
  CPG_Prim.nu[36] = qoco_solver->sol->x[441];
  CPG_Prim.nu[37] = qoco_solver->sol->x[442];
  CPG_Prim.nu[38] = qoco_solver->sol->x[443];
  CPG_Prim.nu[39] = qoco_solver->sol->x[444];
  CPG_Prim.nu[40] = qoco_solver->sol->x[445];
  CPG_Prim.nu[41] = qoco_solver->sol->x[446];
  CPG_Prim.nu[42] = qoco_solver->sol->x[447];
  CPG_Prim.nu[43] = qoco_solver->sol->x[448];
  CPG_Prim.nu[44] = qoco_solver->sol->x[449];
  CPG_Prim.nu[45] = qoco_solver->sol->x[450];
  CPG_Prim.nu[46] = qoco_solver->sol->x[451];
  CPG_Prim.nu[47] = qoco_solver->sol->x[452];
  CPG_Prim.nu[48] = qoco_solver->sol->x[453];
  CPG_Prim.nu[49] = qoco_solver->sol->x[454];
  CPG_Prim.nu[50] = qoco_solver->sol->x[455];
  CPG_Prim.nu[51] = qoco_solver->sol->x[456];
  CPG_Prim.nu[52] = qoco_solver->sol->x[457];
  CPG_Prim.nu[53] = qoco_solver->sol->x[458];
  CPG_Prim.nu[54] = qoco_solver->sol->x[459];
  CPG_Prim.nu[55] = qoco_solver->sol->x[460];
  CPG_Prim.nu[56] = qoco_solver->sol->x[461];
  CPG_Prim.nu[57] = qoco_solver->sol->x[462];
  CPG_Prim.nu[58] = qoco_solver->sol->x[463];
  CPG_Prim.nu[59] = qoco_solver->sol->x[464];
  CPG_Prim.nu[60] = qoco_solver->sol->x[465];
  CPG_Prim.nu[61] = qoco_solver->sol->x[466];
  CPG_Prim.nu[62] = qoco_solver->sol->x[467];
  CPG_Prim.nu[63] = qoco_solver->sol->x[468];
  CPG_Prim.nu[64] = qoco_solver->sol->x[469];
  CPG_Prim.nu[65] = qoco_solver->sol->x[470];
  CPG_Prim.nu[66] = qoco_solver->sol->x[471];
  CPG_Prim.nu[67] = qoco_solver->sol->x[472];
  CPG_Prim.nu[68] = qoco_solver->sol->x[473];
  CPG_Prim.nu[69] = qoco_solver->sol->x[474];
  CPG_Prim.nu[70] = qoco_solver->sol->x[475];
  CPG_Prim.nu[71] = qoco_solver->sol->x[476];
  CPG_Prim.nu[72] = qoco_solver->sol->x[477];
  CPG_Prim.nu[73] = qoco_solver->sol->x[478];
  CPG_Prim.nu[74] = qoco_solver->sol->x[479];
  CPG_Prim.nu[75] = qoco_solver->sol->x[480];
  CPG_Prim.nu[76] = qoco_solver->sol->x[481];
  CPG_Prim.nu[77] = qoco_solver->sol->x[482];
  CPG_Prim.nu[78] = qoco_solver->sol->x[483];
  CPG_Prim.nu[79] = qoco_solver->sol->x[484];
  CPG_Prim.nu[80] = qoco_solver->sol->x[485];
  CPG_Prim.nu[81] = qoco_solver->sol->x[486];
  CPG_Prim.nu[82] = qoco_solver->sol->x[487];
  CPG_Prim.nu[83] = qoco_solver->sol->x[488];
  CPG_Prim.nu[84] = qoco_solver->sol->x[489];
  CPG_Prim.nu[85] = qoco_solver->sol->x[490];
  CPG_Prim.nu[86] = qoco_solver->sol->x[491];
  CPG_Prim.nu[87] = qoco_solver->sol->x[492];
  CPG_Prim.nu[88] = qoco_solver->sol->x[493];
  CPG_Prim.nu[89] = qoco_solver->sol->x[494];
  CPG_Prim.nu[90] = qoco_solver->sol->x[495];
  CPG_Prim.nu[91] = qoco_solver->sol->x[496];
  CPG_Prim.nu[92] = qoco_solver->sol->x[497];
  CPG_Prim.nu[93] = qoco_solver->sol->x[498];
  CPG_Prim.nu[94] = qoco_solver->sol->x[499];
  CPG_Prim.nu[95] = qoco_solver->sol->x[500];
  CPG_Prim.nu[96] = qoco_solver->sol->x[501];
  CPG_Prim.nu[97] = qoco_solver->sol->x[502];
  CPG_Prim.nu[98] = qoco_solver->sol->x[503];
  CPG_Prim.nu[99] = qoco_solver->sol->x[504];
  CPG_Prim.nu[100] = qoco_solver->sol->x[505];
  CPG_Prim.nu[101] = qoco_solver->sol->x[506];
  CPG_Prim.nu[102] = qoco_solver->sol->x[507];
  CPG_Prim.nu[103] = qoco_solver->sol->x[508];
  CPG_Prim.nu[104] = qoco_solver->sol->x[509];
  CPG_Prim.nu[105] = qoco_solver->sol->x[510];
  CPG_Prim.nu[106] = qoco_solver->sol->x[511];
  CPG_Prim.nu[107] = qoco_solver->sol->x[512];
  CPG_Prim.nu[108] = qoco_solver->sol->x[513];
  CPG_Prim.nu[109] = qoco_solver->sol->x[514];
  CPG_Prim.nu[110] = qoco_solver->sol->x[515];
  CPG_Prim.nu[111] = qoco_solver->sol->x[516];
  CPG_Prim.nu[112] = qoco_solver->sol->x[517];
  CPG_Prim.nu[113] = qoco_solver->sol->x[518];
  CPG_Prim.nu[114] = qoco_solver->sol->x[519];
  CPG_Prim.nu[115] = qoco_solver->sol->x[520];
  CPG_Prim.nu[116] = qoco_solver->sol->x[521];
  CPG_Prim.nu[117] = qoco_solver->sol->x[522];
  CPG_Prim.nu[118] = qoco_solver->sol->x[523];
  CPG_Prim.nu[119] = qoco_solver->sol->x[524];
  CPG_Prim.nu[120] = qoco_solver->sol->x[525];
  CPG_Prim.nu[121] = qoco_solver->sol->x[526];
  CPG_Prim.nu[122] = qoco_solver->sol->x[527];
  CPG_Prim.nu[123] = qoco_solver->sol->x[528];
  CPG_Prim.nu[124] = qoco_solver->sol->x[529];
  CPG_Prim.nu[125] = qoco_solver->sol->x[530];
  CPG_Prim.nu[126] = qoco_solver->sol->x[531];
  CPG_Prim.nu[127] = qoco_solver->sol->x[532];
  CPG_Prim.nu[128] = qoco_solver->sol->x[533];
  CPG_Prim.nu[129] = qoco_solver->sol->x[534];
  CPG_Prim.nu[130] = qoco_solver->sol->x[535];
  CPG_Prim.nu[131] = qoco_solver->sol->x[536];
  CPG_Prim.nu[132] = qoco_solver->sol->x[537];
  CPG_Prim.nu[133] = qoco_solver->sol->x[538];
  CPG_Prim.nu[134] = qoco_solver->sol->x[539];
  CPG_Prim.nu[135] = qoco_solver->sol->x[540];
  CPG_Prim.nu[136] = qoco_solver->sol->x[541];
  CPG_Prim.nu[137] = qoco_solver->sol->x[542];
  CPG_Prim.nu[138] = qoco_solver->sol->x[543];
  CPG_Prim.nu[139] = qoco_solver->sol->x[544];
  CPG_Prim.nu[140] = qoco_solver->sol->x[545];
  CPG_Prim.nu[141] = qoco_solver->sol->x[546];
  CPG_Prim.nu[142] = qoco_solver->sol->x[547];
  CPG_Prim.S[0] = qoco_solver->sol->x[394];
  CPG_Prim.S[1] = qoco_solver->sol->x[395];
  CPG_Prim.S[2] = qoco_solver->sol->x[396];
  CPG_Prim.S[3] = qoco_solver->sol->x[397];
  CPG_Prim.S[4] = qoco_solver->sol->x[398];
  CPG_Prim.S[5] = qoco_solver->sol->x[399];
  CPG_Prim.S[6] = qoco_solver->sol->x[400];
  CPG_Prim.S[7] = qoco_solver->sol->x[401];
  CPG_Prim.S[8] = qoco_solver->sol->x[402];
  CPG_Prim.S[9] = qoco_solver->sol->x[403];
  CPG_Prim.S[10] = qoco_solver->sol->x[404];
  CPG_Prim.X[0] = qoco_solver->sol->x[548];
  CPG_Prim.X[1] = qoco_solver->sol->x[549];
  CPG_Prim.X[2] = qoco_solver->sol->x[550];
  CPG_Prim.X[3] = qoco_solver->sol->x[551];
  CPG_Prim.X[4] = qoco_solver->sol->x[552];
  CPG_Prim.X[5] = qoco_solver->sol->x[553];
  CPG_Prim.X[6] = qoco_solver->sol->x[554];
  CPG_Prim.X[7] = qoco_solver->sol->x[555];
  CPG_Prim.X[8] = qoco_solver->sol->x[556];
  CPG_Prim.X[9] = qoco_solver->sol->x[557];
  CPG_Prim.X[10] = qoco_solver->sol->x[558];
  CPG_Prim.X[11] = qoco_solver->sol->x[559];
  CPG_Prim.X[12] = qoco_solver->sol->x[560];
  CPG_Prim.X[13] = qoco_solver->sol->x[561];
  CPG_Prim.X[14] = qoco_solver->sol->x[562];
  CPG_Prim.X[15] = qoco_solver->sol->x[563];
  CPG_Prim.X[16] = qoco_solver->sol->x[564];
  CPG_Prim.X[17] = qoco_solver->sol->x[565];
  CPG_Prim.X[18] = qoco_solver->sol->x[566];
  CPG_Prim.X[19] = qoco_solver->sol->x[567];
  CPG_Prim.X[20] = qoco_solver->sol->x[568];
  CPG_Prim.X[21] = qoco_solver->sol->x[569];
  CPG_Prim.X[22] = qoco_solver->sol->x[570];
  CPG_Prim.X[23] = qoco_solver->sol->x[571];
  CPG_Prim.X[24] = qoco_solver->sol->x[572];
  CPG_Prim.X[25] = qoco_solver->sol->x[573];
  CPG_Prim.X[26] = qoco_solver->sol->x[574];
  CPG_Prim.X[27] = qoco_solver->sol->x[575];
  CPG_Prim.X[28] = qoco_solver->sol->x[576];
  CPG_Prim.X[29] = qoco_solver->sol->x[577];
  CPG_Prim.X[30] = qoco_solver->sol->x[578];
  CPG_Prim.X[31] = qoco_solver->sol->x[579];
  CPG_Prim.X[32] = qoco_solver->sol->x[580];
  CPG_Prim.X[33] = qoco_solver->sol->x[581];
  CPG_Prim.X[34] = qoco_solver->sol->x[582];
  CPG_Prim.X[35] = qoco_solver->sol->x[583];
  CPG_Prim.X[36] = qoco_solver->sol->x[584];
  CPG_Prim.X[37] = qoco_solver->sol->x[585];
  CPG_Prim.X[38] = qoco_solver->sol->x[586];
  CPG_Prim.X[39] = qoco_solver->sol->x[587];
  CPG_Prim.X[40] = qoco_solver->sol->x[588];
  CPG_Prim.X[41] = qoco_solver->sol->x[589];
  CPG_Prim.X[42] = qoco_solver->sol->x[590];
  CPG_Prim.X[43] = qoco_solver->sol->x[591];
  CPG_Prim.X[44] = qoco_solver->sol->x[592];
  CPG_Prim.X[45] = qoco_solver->sol->x[593];
  CPG_Prim.X[46] = qoco_solver->sol->x[594];
  CPG_Prim.X[47] = qoco_solver->sol->x[595];
  CPG_Prim.X[48] = qoco_solver->sol->x[596];
  CPG_Prim.X[49] = qoco_solver->sol->x[597];
  CPG_Prim.X[50] = qoco_solver->sol->x[598];
  CPG_Prim.X[51] = qoco_solver->sol->x[599];
  CPG_Prim.X[52] = qoco_solver->sol->x[600];
  CPG_Prim.X[53] = qoco_solver->sol->x[601];
  CPG_Prim.X[54] = qoco_solver->sol->x[602];
  CPG_Prim.X[55] = qoco_solver->sol->x[603];
  CPG_Prim.X[56] = qoco_solver->sol->x[604];
  CPG_Prim.X[57] = qoco_solver->sol->x[605];
  CPG_Prim.X[58] = qoco_solver->sol->x[606];
  CPG_Prim.X[59] = qoco_solver->sol->x[607];
  CPG_Prim.X[60] = qoco_solver->sol->x[608];
  CPG_Prim.X[61] = qoco_solver->sol->x[609];
  CPG_Prim.X[62] = qoco_solver->sol->x[610];
  CPG_Prim.X[63] = qoco_solver->sol->x[611];
  CPG_Prim.X[64] = qoco_solver->sol->x[612];
  CPG_Prim.X[65] = qoco_solver->sol->x[613];
  CPG_Prim.X[66] = qoco_solver->sol->x[614];
  CPG_Prim.X[67] = qoco_solver->sol->x[615];
  CPG_Prim.X[68] = qoco_solver->sol->x[616];
  CPG_Prim.X[69] = qoco_solver->sol->x[617];
  CPG_Prim.X[70] = qoco_solver->sol->x[618];
  CPG_Prim.X[71] = qoco_solver->sol->x[619];
  CPG_Prim.X[72] = qoco_solver->sol->x[620];
  CPG_Prim.X[73] = qoco_solver->sol->x[621];
  CPG_Prim.X[74] = qoco_solver->sol->x[622];
  CPG_Prim.X[75] = qoco_solver->sol->x[623];
  CPG_Prim.X[76] = qoco_solver->sol->x[624];
  CPG_Prim.X[77] = qoco_solver->sol->x[625];
  CPG_Prim.X[78] = qoco_solver->sol->x[626];
  CPG_Prim.X[79] = qoco_solver->sol->x[627];
  CPG_Prim.X[80] = qoco_solver->sol->x[628];
  CPG_Prim.X[81] = qoco_solver->sol->x[629];
  CPG_Prim.X[82] = qoco_solver->sol->x[630];
  CPG_Prim.X[83] = qoco_solver->sol->x[631];
  CPG_Prim.X[84] = qoco_solver->sol->x[632];
  CPG_Prim.X[85] = qoco_solver->sol->x[633];
  CPG_Prim.X[86] = qoco_solver->sol->x[634];
  CPG_Prim.X[87] = qoco_solver->sol->x[635];
  CPG_Prim.X[88] = qoco_solver->sol->x[636];
  CPG_Prim.X[89] = qoco_solver->sol->x[637];
  CPG_Prim.X[90] = qoco_solver->sol->x[638];
  CPG_Prim.X[91] = qoco_solver->sol->x[639];
  CPG_Prim.X[92] = qoco_solver->sol->x[640];
  CPG_Prim.X[93] = qoco_solver->sol->x[641];
  CPG_Prim.X[94] = qoco_solver->sol->x[642];
  CPG_Prim.X[95] = qoco_solver->sol->x[643];
  CPG_Prim.X[96] = qoco_solver->sol->x[644];
  CPG_Prim.X[97] = qoco_solver->sol->x[645];
  CPG_Prim.X[98] = qoco_solver->sol->x[646];
  CPG_Prim.X[99] = qoco_solver->sol->x[647];
  CPG_Prim.X[100] = qoco_solver->sol->x[648];
  CPG_Prim.X[101] = qoco_solver->sol->x[649];
  CPG_Prim.X[102] = qoco_solver->sol->x[650];
  CPG_Prim.X[103] = qoco_solver->sol->x[651];
  CPG_Prim.X[104] = qoco_solver->sol->x[652];
  CPG_Prim.X[105] = qoco_solver->sol->x[653];
  CPG_Prim.X[106] = qoco_solver->sol->x[654];
  CPG_Prim.X[107] = qoco_solver->sol->x[655];
  CPG_Prim.X[108] = qoco_solver->sol->x[656];
  CPG_Prim.X[109] = qoco_solver->sol->x[657];
  CPG_Prim.X[110] = qoco_solver->sol->x[658];
  CPG_Prim.X[111] = qoco_solver->sol->x[659];
  CPG_Prim.X[112] = qoco_solver->sol->x[660];
  CPG_Prim.X[113] = qoco_solver->sol->x[661];
  CPG_Prim.X[114] = qoco_solver->sol->x[662];
  CPG_Prim.X[115] = qoco_solver->sol->x[663];
  CPG_Prim.X[116] = qoco_solver->sol->x[664];
  CPG_Prim.X[117] = qoco_solver->sol->x[665];
  CPG_Prim.X[118] = qoco_solver->sol->x[666];
  CPG_Prim.X[119] = qoco_solver->sol->x[667];
  CPG_Prim.X[120] = qoco_solver->sol->x[668];
  CPG_Prim.X[121] = qoco_solver->sol->x[669];
  CPG_Prim.X[122] = qoco_solver->sol->x[670];
  CPG_Prim.X[123] = qoco_solver->sol->x[671];
  CPG_Prim.X[124] = qoco_solver->sol->x[672];
  CPG_Prim.X[125] = qoco_solver->sol->x[673];
  CPG_Prim.X[126] = qoco_solver->sol->x[674];
  CPG_Prim.X[127] = qoco_solver->sol->x[675];
  CPG_Prim.X[128] = qoco_solver->sol->x[676];
  CPG_Prim.X[129] = qoco_solver->sol->x[677];
  CPG_Prim.X[130] = qoco_solver->sol->x[678];
  CPG_Prim.X[131] = qoco_solver->sol->x[679];
  CPG_Prim.X[132] = qoco_solver->sol->x[680];
  CPG_Prim.X[133] = qoco_solver->sol->x[681];
  CPG_Prim.X[134] = qoco_solver->sol->x[682];
  CPG_Prim.X[135] = qoco_solver->sol->x[683];
  CPG_Prim.X[136] = qoco_solver->sol->x[684];
  CPG_Prim.X[137] = qoco_solver->sol->x[685];
  CPG_Prim.X[138] = qoco_solver->sol->x[686];
  CPG_Prim.X[139] = qoco_solver->sol->x[687];
  CPG_Prim.X[140] = qoco_solver->sol->x[688];
  CPG_Prim.X[141] = qoco_solver->sol->x[689];
  CPG_Prim.X[142] = qoco_solver->sol->x[690];
  CPG_Prim.X[143] = qoco_solver->sol->x[691];
  CPG_Prim.X[144] = qoco_solver->sol->x[692];
  CPG_Prim.X[145] = qoco_solver->sol->x[693];
  CPG_Prim.X[146] = qoco_solver->sol->x[694];
  CPG_Prim.X[147] = qoco_solver->sol->x[695];
  CPG_Prim.X[148] = qoco_solver->sol->x[696];
  CPG_Prim.X[149] = qoco_solver->sol->x[697];
  CPG_Prim.X[150] = qoco_solver->sol->x[698];
  CPG_Prim.X[151] = qoco_solver->sol->x[699];
  CPG_Prim.X[152] = qoco_solver->sol->x[700];
  CPG_Prim.X[153] = qoco_solver->sol->x[701];
  CPG_Prim.X[154] = qoco_solver->sol->x[702];
  CPG_Prim.X[155] = qoco_solver->sol->x[703];
  CPG_Prim.U[0] = qoco_solver->sol->x[704];
  CPG_Prim.U[1] = qoco_solver->sol->x[705];
  CPG_Prim.U[2] = qoco_solver->sol->x[706];
  CPG_Prim.U[3] = qoco_solver->sol->x[707];
  CPG_Prim.U[4] = qoco_solver->sol->x[708];
  CPG_Prim.U[5] = qoco_solver->sol->x[709];
  CPG_Prim.U[6] = qoco_solver->sol->x[710];
  CPG_Prim.U[7] = qoco_solver->sol->x[711];
  CPG_Prim.U[8] = qoco_solver->sol->x[712];
  CPG_Prim.U[9] = qoco_solver->sol->x[713];
  CPG_Prim.U[10] = qoco_solver->sol->x[714];
  CPG_Prim.U[11] = qoco_solver->sol->x[715];
  CPG_Prim.U[12] = qoco_solver->sol->x[716];
  CPG_Prim.U[13] = qoco_solver->sol->x[717];
  CPG_Prim.U[14] = qoco_solver->sol->x[718];
  CPG_Prim.U[15] = qoco_solver->sol->x[719];
  CPG_Prim.U[16] = qoco_solver->sol->x[720];
  CPG_Prim.U[17] = qoco_solver->sol->x[721];
  CPG_Prim.U[18] = qoco_solver->sol->x[722];
  CPG_Prim.U[19] = qoco_solver->sol->x[723];
  CPG_Prim.U[20] = qoco_solver->sol->x[724];
  CPG_Prim.U[21] = qoco_solver->sol->x[725];
  CPG_Prim.U[22] = qoco_solver->sol->x[726];
  CPG_Prim.U[23] = qoco_solver->sol->x[727];
  CPG_Prim.U[24] = qoco_solver->sol->x[728];
  CPG_Prim.U[25] = qoco_solver->sol->x[729];
  CPG_Prim.U[26] = qoco_solver->sol->x[730];
  CPG_Prim.U[27] = qoco_solver->sol->x[731];
  CPG_Prim.U[28] = qoco_solver->sol->x[732];
  CPG_Prim.U[29] = qoco_solver->sol->x[733];
  CPG_Prim.U[30] = qoco_solver->sol->x[734];
  CPG_Prim.U[31] = qoco_solver->sol->x[735];
  CPG_Prim.U[32] = qoco_solver->sol->x[736];
  CPG_Prim.U[33] = qoco_solver->sol->x[737];
  CPG_Prim.U[34] = qoco_solver->sol->x[738];
  CPG_Prim.U[35] = qoco_solver->sol->x[739];
  CPG_Prim.U[36] = qoco_solver->sol->x[740];
  CPG_Prim.U[37] = qoco_solver->sol->x[741];
  CPG_Prim.U[38] = qoco_solver->sol->x[742];
  CPG_Prim.U[39] = qoco_solver->sol->x[743];
  CPG_Prim.U[40] = qoco_solver->sol->x[744];
  CPG_Prim.U[41] = qoco_solver->sol->x[745];
  CPG_Prim.U[42] = qoco_solver->sol->x[746];
  CPG_Prim.U[43] = qoco_solver->sol->x[747];
  CPG_Prim.U[44] = qoco_solver->sol->x[748];
  CPG_Prim.U[45] = qoco_solver->sol->x[749];
  CPG_Prim.U[46] = qoco_solver->sol->x[750];
  CPG_Prim.U[47] = qoco_solver->sol->x[751];
}

// Retrieve dual solution in terms of user-defined constraints
void cpg_retrieve_dual(){
  CPG_Dual.d0[0] = qoco_solver->sol->y[0];
  CPG_Dual.d0[1] = qoco_solver->sol->y[1];
  CPG_Dual.d0[2] = qoco_solver->sol->y[2];
  CPG_Dual.d0[3] = qoco_solver->sol->y[3];
  CPG_Dual.d0[4] = qoco_solver->sol->y[4];
  CPG_Dual.d0[5] = qoco_solver->sol->y[5];
  CPG_Dual.d0[6] = qoco_solver->sol->y[6];
  CPG_Dual.d0[7] = qoco_solver->sol->y[7];
  CPG_Dual.d0[8] = qoco_solver->sol->y[8];
  CPG_Dual.d0[9] = qoco_solver->sol->y[9];
  CPG_Dual.d0[10] = qoco_solver->sol->y[10];
  CPG_Dual.d0[11] = qoco_solver->sol->y[11];
  CPG_Dual.d0[12] = qoco_solver->sol->y[12];
  CPG_Dual.d1[0] = qoco_solver->sol->y[13];
  CPG_Dual.d1[1] = qoco_solver->sol->y[14];
  CPG_Dual.d1[2] = qoco_solver->sol->y[15];
  CPG_Dual.d1[3] = qoco_solver->sol->y[16];
  CPG_Dual.d1[4] = qoco_solver->sol->y[17];
  CPG_Dual.d1[5] = qoco_solver->sol->y[18];
  CPG_Dual.d1[6] = qoco_solver->sol->y[19];
  CPG_Dual.d1[7] = qoco_solver->sol->y[20];
  CPG_Dual.d1[8] = qoco_solver->sol->y[21];
  CPG_Dual.d1[9] = qoco_solver->sol->y[22];
  CPG_Dual.d1[10] = qoco_solver->sol->y[23];
  CPG_Dual.d1[11] = qoco_solver->sol->y[24];
  CPG_Dual.d1[12] = qoco_solver->sol->y[25];
  CPG_Dual.d2[0] = qoco_solver->sol->y[26];
  CPG_Dual.d2[1] = qoco_solver->sol->y[27];
  CPG_Dual.d2[2] = qoco_solver->sol->y[28];
  CPG_Dual.d2[3] = qoco_solver->sol->y[29];
  CPG_Dual.d2[4] = qoco_solver->sol->y[30];
  CPG_Dual.d2[5] = qoco_solver->sol->y[31];
  CPG_Dual.d2[6] = qoco_solver->sol->y[32];
  CPG_Dual.d2[7] = qoco_solver->sol->y[33];
  CPG_Dual.d2[8] = qoco_solver->sol->y[34];
  CPG_Dual.d2[9] = qoco_solver->sol->y[35];
  CPG_Dual.d2[10] = qoco_solver->sol->y[36];
  CPG_Dual.d2[11] = qoco_solver->sol->y[37];
  CPG_Dual.d2[12] = qoco_solver->sol->y[38];
  CPG_Dual.d3[0] = qoco_solver->sol->y[39];
  CPG_Dual.d3[1] = qoco_solver->sol->y[40];
  CPG_Dual.d3[2] = qoco_solver->sol->y[41];
  CPG_Dual.d3[3] = qoco_solver->sol->y[42];
  CPG_Dual.d3[4] = qoco_solver->sol->y[43];
  CPG_Dual.d3[5] = qoco_solver->sol->y[44];
  CPG_Dual.d3[6] = qoco_solver->sol->y[45];
  CPG_Dual.d3[7] = qoco_solver->sol->y[46];
  CPG_Dual.d3[8] = qoco_solver->sol->y[47];
  CPG_Dual.d3[9] = qoco_solver->sol->y[48];
  CPG_Dual.d3[10] = qoco_solver->sol->y[49];
  CPG_Dual.d3[11] = qoco_solver->sol->y[50];
  CPG_Dual.d3[12] = qoco_solver->sol->y[51];
  CPG_Dual.d4[0] = qoco_solver->sol->y[52];
  CPG_Dual.d4[1] = qoco_solver->sol->y[53];
  CPG_Dual.d4[2] = qoco_solver->sol->y[54];
  CPG_Dual.d4[3] = qoco_solver->sol->y[55];
  CPG_Dual.d4[4] = qoco_solver->sol->y[56];
  CPG_Dual.d4[5] = qoco_solver->sol->y[57];
  CPG_Dual.d4[6] = qoco_solver->sol->y[58];
  CPG_Dual.d4[7] = qoco_solver->sol->y[59];
  CPG_Dual.d4[8] = qoco_solver->sol->y[60];
  CPG_Dual.d4[9] = qoco_solver->sol->y[61];
  CPG_Dual.d4[10] = qoco_solver->sol->y[62];
  CPG_Dual.d4[11] = qoco_solver->sol->y[63];
  CPG_Dual.d4[12] = qoco_solver->sol->y[64];
  CPG_Dual.d5[0] = qoco_solver->sol->y[65];
  CPG_Dual.d5[1] = qoco_solver->sol->y[66];
  CPG_Dual.d5[2] = qoco_solver->sol->y[67];
  CPG_Dual.d5[3] = qoco_solver->sol->y[68];
  CPG_Dual.d5[4] = qoco_solver->sol->y[69];
  CPG_Dual.d5[5] = qoco_solver->sol->y[70];
  CPG_Dual.d5[6] = qoco_solver->sol->y[71];
  CPG_Dual.d5[7] = qoco_solver->sol->y[72];
  CPG_Dual.d5[8] = qoco_solver->sol->y[73];
  CPG_Dual.d5[9] = qoco_solver->sol->y[74];
  CPG_Dual.d5[10] = qoco_solver->sol->y[75];
  CPG_Dual.d5[11] = qoco_solver->sol->y[76];
  CPG_Dual.d5[12] = qoco_solver->sol->y[77];
  CPG_Dual.d6[0] = qoco_solver->sol->y[78];
  CPG_Dual.d6[1] = qoco_solver->sol->y[79];
  CPG_Dual.d6[2] = qoco_solver->sol->y[80];
  CPG_Dual.d6[3] = qoco_solver->sol->y[81];
  CPG_Dual.d6[4] = qoco_solver->sol->y[82];
  CPG_Dual.d6[5] = qoco_solver->sol->y[83];
  CPG_Dual.d6[6] = qoco_solver->sol->y[84];
  CPG_Dual.d6[7] = qoco_solver->sol->y[85];
  CPG_Dual.d6[8] = qoco_solver->sol->y[86];
  CPG_Dual.d6[9] = qoco_solver->sol->y[87];
  CPG_Dual.d6[10] = qoco_solver->sol->y[88];
  CPG_Dual.d6[11] = qoco_solver->sol->y[89];
  CPG_Dual.d6[12] = qoco_solver->sol->y[90];
  CPG_Dual.d7[0] = qoco_solver->sol->y[91];
  CPG_Dual.d7[1] = qoco_solver->sol->y[92];
  CPG_Dual.d7[2] = qoco_solver->sol->y[93];
  CPG_Dual.d7[3] = qoco_solver->sol->y[94];
  CPG_Dual.d7[4] = qoco_solver->sol->y[95];
  CPG_Dual.d7[5] = qoco_solver->sol->y[96];
  CPG_Dual.d7[6] = qoco_solver->sol->y[97];
  CPG_Dual.d7[7] = qoco_solver->sol->y[98];
  CPG_Dual.d7[8] = qoco_solver->sol->y[99];
  CPG_Dual.d7[9] = qoco_solver->sol->y[100];
  CPG_Dual.d7[10] = qoco_solver->sol->y[101];
  CPG_Dual.d7[11] = qoco_solver->sol->y[102];
  CPG_Dual.d7[12] = qoco_solver->sol->y[103];
  CPG_Dual.d8[0] = qoco_solver->sol->y[104];
  CPG_Dual.d8[1] = qoco_solver->sol->y[105];
  CPG_Dual.d8[2] = qoco_solver->sol->y[106];
  CPG_Dual.d8[3] = qoco_solver->sol->y[107];
  CPG_Dual.d8[4] = qoco_solver->sol->y[108];
  CPG_Dual.d8[5] = qoco_solver->sol->y[109];
  CPG_Dual.d8[6] = qoco_solver->sol->y[110];
  CPG_Dual.d8[7] = qoco_solver->sol->y[111];
  CPG_Dual.d8[8] = qoco_solver->sol->y[112];
  CPG_Dual.d8[9] = qoco_solver->sol->y[113];
  CPG_Dual.d8[10] = qoco_solver->sol->y[114];
  CPG_Dual.d8[11] = qoco_solver->sol->y[115];
  CPG_Dual.d8[12] = qoco_solver->sol->y[116];
  CPG_Dual.d9[0] = qoco_solver->sol->y[117];
  CPG_Dual.d9[1] = qoco_solver->sol->y[118];
  CPG_Dual.d9[2] = qoco_solver->sol->y[119];
  CPG_Dual.d9[3] = qoco_solver->sol->y[120];
  CPG_Dual.d9[4] = qoco_solver->sol->y[121];
  CPG_Dual.d9[5] = qoco_solver->sol->y[122];
  CPG_Dual.d9[6] = qoco_solver->sol->y[123];
  CPG_Dual.d9[7] = qoco_solver->sol->y[124];
  CPG_Dual.d9[8] = qoco_solver->sol->y[125];
  CPG_Dual.d9[9] = qoco_solver->sol->y[126];
  CPG_Dual.d9[10] = qoco_solver->sol->y[127];
  CPG_Dual.d9[11] = qoco_solver->sol->y[128];
  CPG_Dual.d9[12] = qoco_solver->sol->y[129];
  CPG_Dual.d10[0] = qoco_solver->sol->y[130];
  CPG_Dual.d10[1] = qoco_solver->sol->y[131];
  CPG_Dual.d10[2] = qoco_solver->sol->y[132];
  CPG_Dual.d10[3] = qoco_solver->sol->y[133];
  CPG_Dual.d10[4] = qoco_solver->sol->y[134];
  CPG_Dual.d10[5] = qoco_solver->sol->y[135];
  CPG_Dual.d10[6] = qoco_solver->sol->y[136];
  CPG_Dual.d10[7] = qoco_solver->sol->y[137];
  CPG_Dual.d10[8] = qoco_solver->sol->y[138];
  CPG_Dual.d10[9] = qoco_solver->sol->y[139];
  CPG_Dual.d10[10] = qoco_solver->sol->y[140];
  CPG_Dual.d10[11] = qoco_solver->sol->y[141];
  CPG_Dual.d10[12] = qoco_solver->sol->y[142];
  CPG_Dual.d11[0] = qoco_solver->sol->y[143];
  CPG_Dual.d11[1] = qoco_solver->sol->y[144];
  CPG_Dual.d11[2] = qoco_solver->sol->y[145];
  CPG_Dual.d11[3] = qoco_solver->sol->y[146];
  CPG_Dual.d11[4] = qoco_solver->sol->y[147];
  CPG_Dual.d11[5] = qoco_solver->sol->y[148];
  CPG_Dual.d11[6] = qoco_solver->sol->y[149];
  CPG_Dual.d11[7] = qoco_solver->sol->y[150];
  CPG_Dual.d11[8] = qoco_solver->sol->y[151];
  CPG_Dual.d11[9] = qoco_solver->sol->y[152];
  CPG_Dual.d11[10] = qoco_solver->sol->y[153];
  CPG_Dual.d11[11] = qoco_solver->sol->y[154];
  CPG_Dual.d11[12] = qoco_solver->sol->y[155];
  CPG_Dual.d11[13] = qoco_solver->sol->y[156];
  CPG_Dual.d11[14] = qoco_solver->sol->y[157];
  CPG_Dual.d11[15] = qoco_solver->sol->y[158];
  CPG_Dual.d11[16] = qoco_solver->sol->y[159];
  CPG_Dual.d11[17] = qoco_solver->sol->y[160];
  CPG_Dual.d11[18] = qoco_solver->sol->y[161];
  CPG_Dual.d11[19] = qoco_solver->sol->y[162];
  CPG_Dual.d11[20] = qoco_solver->sol->y[163];
  CPG_Dual.d11[21] = qoco_solver->sol->y[164];
  CPG_Dual.d11[22] = qoco_solver->sol->y[165];
  CPG_Dual.d11[23] = qoco_solver->sol->y[166];
  CPG_Dual.d11[24] = qoco_solver->sol->y[167];
  CPG_Dual.d11[25] = qoco_solver->sol->y[168];
  CPG_Dual.d11[26] = qoco_solver->sol->y[169];
  CPG_Dual.d11[27] = qoco_solver->sol->y[170];
  CPG_Dual.d11[28] = qoco_solver->sol->y[171];
  CPG_Dual.d11[29] = qoco_solver->sol->y[172];
  CPG_Dual.d11[30] = qoco_solver->sol->y[173];
  CPG_Dual.d11[31] = qoco_solver->sol->y[174];
  CPG_Dual.d11[32] = qoco_solver->sol->y[175];
  CPG_Dual.d11[33] = qoco_solver->sol->y[176];
  CPG_Dual.d11[34] = qoco_solver->sol->y[177];
  CPG_Dual.d11[35] = qoco_solver->sol->y[178];
  CPG_Dual.d11[36] = qoco_solver->sol->y[179];
  CPG_Dual.d11[37] = qoco_solver->sol->y[180];
  CPG_Dual.d11[38] = qoco_solver->sol->y[181];
  CPG_Dual.d11[39] = qoco_solver->sol->y[182];
  CPG_Dual.d11[40] = qoco_solver->sol->y[183];
  CPG_Dual.d11[41] = qoco_solver->sol->y[184];
  CPG_Dual.d11[42] = qoco_solver->sol->y[185];
  CPG_Dual.d11[43] = qoco_solver->sol->y[186];
  CPG_Dual.d11[44] = qoco_solver->sol->y[187];
  CPG_Dual.d11[45] = qoco_solver->sol->y[188];
  CPG_Dual.d11[46] = qoco_solver->sol->y[189];
  CPG_Dual.d11[47] = qoco_solver->sol->y[190];
  CPG_Dual.d11[48] = qoco_solver->sol->y[191];
  CPG_Dual.d11[49] = qoco_solver->sol->y[192];
  CPG_Dual.d11[50] = qoco_solver->sol->y[193];
  CPG_Dual.d11[51] = qoco_solver->sol->y[194];
  CPG_Dual.d11[52] = qoco_solver->sol->y[195];
  CPG_Dual.d11[53] = qoco_solver->sol->y[196];
  CPG_Dual.d11[54] = qoco_solver->sol->y[197];
  CPG_Dual.d11[55] = qoco_solver->sol->y[198];
  CPG_Dual.d11[56] = qoco_solver->sol->y[199];
  CPG_Dual.d11[57] = qoco_solver->sol->y[200];
  CPG_Dual.d11[58] = qoco_solver->sol->y[201];
  CPG_Dual.d11[59] = qoco_solver->sol->y[202];
  CPG_Dual.d11[60] = qoco_solver->sol->y[203];
  CPG_Dual.d11[61] = qoco_solver->sol->y[204];
  CPG_Dual.d11[62] = qoco_solver->sol->y[205];
  CPG_Dual.d11[63] = qoco_solver->sol->y[206];
  CPG_Dual.d11[64] = qoco_solver->sol->y[207];
  CPG_Dual.d11[65] = qoco_solver->sol->y[208];
  CPG_Dual.d11[66] = qoco_solver->sol->y[209];
  CPG_Dual.d11[67] = qoco_solver->sol->y[210];
  CPG_Dual.d11[68] = qoco_solver->sol->y[211];
  CPG_Dual.d11[69] = qoco_solver->sol->y[212];
  CPG_Dual.d11[70] = qoco_solver->sol->y[213];
  CPG_Dual.d11[71] = qoco_solver->sol->y[214];
  CPG_Dual.d11[72] = qoco_solver->sol->y[215];
  CPG_Dual.d11[73] = qoco_solver->sol->y[216];
  CPG_Dual.d11[74] = qoco_solver->sol->y[217];
  CPG_Dual.d11[75] = qoco_solver->sol->y[218];
  CPG_Dual.d11[76] = qoco_solver->sol->y[219];
  CPG_Dual.d11[77] = qoco_solver->sol->y[220];
  CPG_Dual.d11[78] = qoco_solver->sol->y[221];
  CPG_Dual.d11[79] = qoco_solver->sol->y[222];
  CPG_Dual.d11[80] = qoco_solver->sol->y[223];
  CPG_Dual.d11[81] = qoco_solver->sol->y[224];
  CPG_Dual.d11[82] = qoco_solver->sol->y[225];
  CPG_Dual.d11[83] = qoco_solver->sol->y[226];
  CPG_Dual.d11[84] = qoco_solver->sol->y[227];
  CPG_Dual.d11[85] = qoco_solver->sol->y[228];
  CPG_Dual.d11[86] = qoco_solver->sol->y[229];
  CPG_Dual.d11[87] = qoco_solver->sol->y[230];
  CPG_Dual.d11[88] = qoco_solver->sol->y[231];
  CPG_Dual.d11[89] = qoco_solver->sol->y[232];
  CPG_Dual.d11[90] = qoco_solver->sol->y[233];
  CPG_Dual.d11[91] = qoco_solver->sol->y[234];
  CPG_Dual.d11[92] = qoco_solver->sol->y[235];
  CPG_Dual.d11[93] = qoco_solver->sol->y[236];
  CPG_Dual.d11[94] = qoco_solver->sol->y[237];
  CPG_Dual.d11[95] = qoco_solver->sol->y[238];
  CPG_Dual.d11[96] = qoco_solver->sol->y[239];
  CPG_Dual.d11[97] = qoco_solver->sol->y[240];
  CPG_Dual.d11[98] = qoco_solver->sol->y[241];
  CPG_Dual.d11[99] = qoco_solver->sol->y[242];
  CPG_Dual.d11[100] = qoco_solver->sol->y[243];
  CPG_Dual.d11[101] = qoco_solver->sol->y[244];
  CPG_Dual.d11[102] = qoco_solver->sol->y[245];
  CPG_Dual.d11[103] = qoco_solver->sol->y[246];
  CPG_Dual.d11[104] = qoco_solver->sol->y[247];
  CPG_Dual.d11[105] = qoco_solver->sol->y[248];
  CPG_Dual.d11[106] = qoco_solver->sol->y[249];
  CPG_Dual.d11[107] = qoco_solver->sol->y[250];
  CPG_Dual.d11[108] = qoco_solver->sol->y[251];
  CPG_Dual.d11[109] = qoco_solver->sol->y[252];
  CPG_Dual.d11[110] = qoco_solver->sol->y[253];
  CPG_Dual.d11[111] = qoco_solver->sol->y[254];
  CPG_Dual.d11[112] = qoco_solver->sol->y[255];
  CPG_Dual.d11[113] = qoco_solver->sol->y[256];
  CPG_Dual.d11[114] = qoco_solver->sol->y[257];
  CPG_Dual.d11[115] = qoco_solver->sol->y[258];
  CPG_Dual.d11[116] = qoco_solver->sol->y[259];
  CPG_Dual.d11[117] = qoco_solver->sol->y[260];
  CPG_Dual.d11[118] = qoco_solver->sol->y[261];
  CPG_Dual.d11[119] = qoco_solver->sol->y[262];
  CPG_Dual.d11[120] = qoco_solver->sol->y[263];
  CPG_Dual.d11[121] = qoco_solver->sol->y[264];
  CPG_Dual.d11[122] = qoco_solver->sol->y[265];
  CPG_Dual.d11[123] = qoco_solver->sol->y[266];
  CPG_Dual.d11[124] = qoco_solver->sol->y[267];
  CPG_Dual.d11[125] = qoco_solver->sol->y[268];
  CPG_Dual.d11[126] = qoco_solver->sol->y[269];
  CPG_Dual.d11[127] = qoco_solver->sol->y[270];
  CPG_Dual.d11[128] = qoco_solver->sol->y[271];
  CPG_Dual.d11[129] = qoco_solver->sol->y[272];
  CPG_Dual.d11[130] = qoco_solver->sol->y[273];
  CPG_Dual.d11[131] = qoco_solver->sol->y[274];
  CPG_Dual.d11[132] = qoco_solver->sol->y[275];
  CPG_Dual.d11[133] = qoco_solver->sol->y[276];
  CPG_Dual.d11[134] = qoco_solver->sol->y[277];
  CPG_Dual.d11[135] = qoco_solver->sol->y[278];
  CPG_Dual.d11[136] = qoco_solver->sol->y[279];
  CPG_Dual.d11[137] = qoco_solver->sol->y[280];
  CPG_Dual.d11[138] = qoco_solver->sol->y[281];
  CPG_Dual.d11[139] = qoco_solver->sol->y[282];
  CPG_Dual.d11[140] = qoco_solver->sol->y[283];
  CPG_Dual.d11[141] = qoco_solver->sol->y[284];
  CPG_Dual.d11[142] = qoco_solver->sol->y[285];
  CPG_Dual.d11[143] = qoco_solver->sol->y[286];
  CPG_Dual.d11[144] = qoco_solver->sol->y[287];
  CPG_Dual.d11[145] = qoco_solver->sol->y[288];
  CPG_Dual.d11[146] = qoco_solver->sol->y[289];
  CPG_Dual.d11[147] = qoco_solver->sol->y[290];
  CPG_Dual.d11[148] = qoco_solver->sol->y[291];
  CPG_Dual.d11[149] = qoco_solver->sol->y[292];
  CPG_Dual.d11[150] = qoco_solver->sol->y[293];
  CPG_Dual.d11[151] = qoco_solver->sol->y[294];
  CPG_Dual.d11[152] = qoco_solver->sol->y[295];
  CPG_Dual.d11[153] = qoco_solver->sol->y[296];
  CPG_Dual.d11[154] = qoco_solver->sol->y[297];
  CPG_Dual.d11[155] = qoco_solver->sol->y[298];
  CPG_Dual.d12[0] = qoco_solver->sol->y[299];
  CPG_Dual.d12[1] = qoco_solver->sol->y[300];
  CPG_Dual.d12[2] = qoco_solver->sol->y[301];
  CPG_Dual.d12[3] = qoco_solver->sol->y[302];
  CPG_Dual.d12[4] = qoco_solver->sol->y[303];
  CPG_Dual.d12[5] = qoco_solver->sol->y[304];
  CPG_Dual.d12[6] = qoco_solver->sol->y[305];
  CPG_Dual.d12[7] = qoco_solver->sol->y[306];
  CPG_Dual.d12[8] = qoco_solver->sol->y[307];
  CPG_Dual.d12[9] = qoco_solver->sol->y[308];
  CPG_Dual.d12[10] = qoco_solver->sol->y[309];
  CPG_Dual.d12[11] = qoco_solver->sol->y[310];
  CPG_Dual.d12[12] = qoco_solver->sol->y[311];
  CPG_Dual.d12[13] = qoco_solver->sol->y[312];
  CPG_Dual.d12[14] = qoco_solver->sol->y[313];
  CPG_Dual.d12[15] = qoco_solver->sol->y[314];
  CPG_Dual.d12[16] = qoco_solver->sol->y[315];
  CPG_Dual.d12[17] = qoco_solver->sol->y[316];
  CPG_Dual.d12[18] = qoco_solver->sol->y[317];
  CPG_Dual.d12[19] = qoco_solver->sol->y[318];
  CPG_Dual.d12[20] = qoco_solver->sol->y[319];
  CPG_Dual.d12[21] = qoco_solver->sol->y[320];
  CPG_Dual.d12[22] = qoco_solver->sol->y[321];
  CPG_Dual.d12[23] = qoco_solver->sol->y[322];
  CPG_Dual.d12[24] = qoco_solver->sol->y[323];
  CPG_Dual.d12[25] = qoco_solver->sol->y[324];
  CPG_Dual.d12[26] = qoco_solver->sol->y[325];
  CPG_Dual.d12[27] = qoco_solver->sol->y[326];
  CPG_Dual.d12[28] = qoco_solver->sol->y[327];
  CPG_Dual.d12[29] = qoco_solver->sol->y[328];
  CPG_Dual.d12[30] = qoco_solver->sol->y[329];
  CPG_Dual.d12[31] = qoco_solver->sol->y[330];
  CPG_Dual.d12[32] = qoco_solver->sol->y[331];
  CPG_Dual.d12[33] = qoco_solver->sol->y[332];
  CPG_Dual.d12[34] = qoco_solver->sol->y[333];
  CPG_Dual.d12[35] = qoco_solver->sol->y[334];
  CPG_Dual.d12[36] = qoco_solver->sol->y[335];
  CPG_Dual.d12[37] = qoco_solver->sol->y[336];
  CPG_Dual.d12[38] = qoco_solver->sol->y[337];
  CPG_Dual.d12[39] = qoco_solver->sol->y[338];
  CPG_Dual.d12[40] = qoco_solver->sol->y[339];
  CPG_Dual.d12[41] = qoco_solver->sol->y[340];
  CPG_Dual.d12[42] = qoco_solver->sol->y[341];
  CPG_Dual.d12[43] = qoco_solver->sol->y[342];
  CPG_Dual.d12[44] = qoco_solver->sol->y[343];
  CPG_Dual.d12[45] = qoco_solver->sol->y[344];
  CPG_Dual.d12[46] = qoco_solver->sol->y[345];
  CPG_Dual.d12[47] = qoco_solver->sol->y[346];
  CPG_Dual.d13[0] = qoco_solver->sol->y[347];
  CPG_Dual.d13[1] = qoco_solver->sol->y[348];
  CPG_Dual.d13[2] = qoco_solver->sol->y[349];
  CPG_Dual.d13[3] = qoco_solver->sol->y[350];
  CPG_Dual.d13[4] = qoco_solver->sol->y[351];
  CPG_Dual.d13[5] = qoco_solver->sol->y[352];
  CPG_Dual.d13[6] = qoco_solver->sol->y[353];
  CPG_Dual.d13[7] = qoco_solver->sol->y[354];
  CPG_Dual.d13[8] = qoco_solver->sol->y[355];
  CPG_Dual.d13[9] = qoco_solver->sol->y[356];
  CPG_Dual.d13[10] = qoco_solver->sol->y[357];
  CPG_Dual.d14[0] = qoco_solver->sol->z[319];
  CPG_Dual.d14[1] = qoco_solver->sol->z[320];
  CPG_Dual.d14[2] = qoco_solver->sol->z[321];
  CPG_Dual.d14[3] = qoco_solver->sol->z[322];
  CPG_Dual.d14[4] = qoco_solver->sol->z[323];
  CPG_Dual.d14[5] = qoco_solver->sol->z[324];
  CPG_Dual.d14[6] = qoco_solver->sol->z[325];
  CPG_Dual.d14[7] = qoco_solver->sol->z[326];
  CPG_Dual.d14[8] = qoco_solver->sol->z[327];
  CPG_Dual.d14[9] = qoco_solver->sol->z[328];
  CPG_Dual.d14[10] = qoco_solver->sol->z[329];
  CPG_Dual.d15 = qoco_solver->sol->y[358];
  CPG_Dual.d16[0] = qoco_solver->sol->z[330];
  CPG_Dual.d16[1] = qoco_solver->sol->z[331];
  CPG_Dual.d16[2] = qoco_solver->sol->z[332];
  CPG_Dual.d16[3] = qoco_solver->sol->z[333];
  CPG_Dual.d16[4] = qoco_solver->sol->z[334];
  CPG_Dual.d16[5] = qoco_solver->sol->z[335];
  CPG_Dual.d16[6] = qoco_solver->sol->z[336];
  CPG_Dual.d16[7] = qoco_solver->sol->z[337];
  CPG_Dual.d16[8] = qoco_solver->sol->z[338];
  CPG_Dual.d16[9] = qoco_solver->sol->z[339];
  CPG_Dual.d16[10] = qoco_solver->sol->z[340];
  CPG_Dual.d17[0] = qoco_solver->sol->y[359];
  CPG_Dual.d17[1] = qoco_solver->sol->y[360];
  CPG_Dual.d17[2] = qoco_solver->sol->y[361];
  CPG_Dual.d17[3] = qoco_solver->sol->y[362];
  CPG_Dual.d17[4] = qoco_solver->sol->y[363];
  CPG_Dual.d17[5] = qoco_solver->sol->y[364];
  CPG_Dual.d17[6] = qoco_solver->sol->y[365];
  CPG_Dual.d17[7] = qoco_solver->sol->y[366];
  CPG_Dual.d18[0] = qoco_solver->sol->y[367];
  CPG_Dual.d18[1] = qoco_solver->sol->y[368];
  CPG_Dual.d18[2] = qoco_solver->sol->y[369];
  CPG_Dual.d18[3] = qoco_solver->sol->y[370];
  CPG_Dual.d18[4] = qoco_solver->sol->y[371];
  CPG_Dual.d18[5] = qoco_solver->sol->y[372];
  CPG_Dual.d18[6] = qoco_solver->sol->y[373];
  CPG_Dual.d18[7] = qoco_solver->sol->y[374];
  CPG_Dual.d19[0] = qoco_solver->sol->y[375];
  CPG_Dual.d19[1] = qoco_solver->sol->y[376];
  CPG_Dual.d19[2] = qoco_solver->sol->y[377];
  CPG_Dual.d20[0] = qoco_solver->sol->y[378];
  CPG_Dual.d20[1] = qoco_solver->sol->y[379];
  CPG_Dual.d20[2] = qoco_solver->sol->y[380];
  CPG_Dual.d21[0] = qoco_solver->sol->y[381];
  CPG_Dual.d21[1] = qoco_solver->sol->y[382];
  CPG_Dual.d21[2] = qoco_solver->sol->y[383];
  CPG_Dual.d21[3] = qoco_solver->sol->y[384];
  CPG_Dual.d22[0] = qoco_solver->sol->y[385];
  CPG_Dual.d22[1] = qoco_solver->sol->y[386];
  CPG_Dual.d22[2] = qoco_solver->sol->y[387];
  CPG_Dual.d22[3] = qoco_solver->sol->y[388];
  CPG_Dual.d23[0] = qoco_solver->sol->z[341];
  CPG_Dual.d23[1] = qoco_solver->sol->z[342];
  CPG_Dual.d23[2] = qoco_solver->sol->z[343];
  CPG_Dual.d23[3] = qoco_solver->sol->z[344];
  CPG_Dual.d23[4] = qoco_solver->sol->z[345];
  CPG_Dual.d23[5] = qoco_solver->sol->z[346];
  CPG_Dual.d23[6] = qoco_solver->sol->z[347];
  CPG_Dual.d23[7] = qoco_solver->sol->z[348];
  CPG_Dual.d23[8] = qoco_solver->sol->z[349];
  CPG_Dual.d23[9] = qoco_solver->sol->z[350];
  CPG_Dual.d23[10] = qoco_solver->sol->z[351];
  CPG_Dual.d23[11] = qoco_solver->sol->z[352];
  CPG_Dual.d24[0] = qoco_solver->sol->z[353];
  CPG_Dual.d24[1] = qoco_solver->sol->z[354];
  CPG_Dual.d24[2] = qoco_solver->sol->z[355];
  CPG_Dual.d24[3] = qoco_solver->sol->z[356];
  CPG_Dual.d24[4] = qoco_solver->sol->z[357];
  CPG_Dual.d24[5] = qoco_solver->sol->z[358];
  CPG_Dual.d24[6] = qoco_solver->sol->z[359];
  CPG_Dual.d24[7] = qoco_solver->sol->z[360];
  CPG_Dual.d24[8] = qoco_solver->sol->z[361];
  CPG_Dual.d24[9] = qoco_solver->sol->z[362];
  CPG_Dual.d24[10] = qoco_solver->sol->z[363];
  CPG_Dual.d24[11] = qoco_solver->sol->z[364];
  CPG_Dual.d25[0] = qoco_solver->sol->z[437];
  CPG_Dual.d25[1] = qoco_solver->sol->z[438];
  CPG_Dual.d25[2] = qoco_solver->sol->z[439];
  CPG_Dual.d25[3] = qoco_solver->sol->z[440];
  CPG_Dual.d25[4] = qoco_solver->sol->z[441];
  CPG_Dual.d25[5] = qoco_solver->sol->z[442];
  CPG_Dual.d25[6] = qoco_solver->sol->z[443];
  CPG_Dual.d25[7] = qoco_solver->sol->z[444];
  CPG_Dual.d25[8] = qoco_solver->sol->z[445];
  CPG_Dual.d25[9] = qoco_solver->sol->z[446];
  CPG_Dual.d25[10] = qoco_solver->sol->z[447];
  CPG_Dual.d25[11] = qoco_solver->sol->z[448];
  CPG_Dual.d25[12] = qoco_solver->sol->z[449];
  CPG_Dual.d25[13] = qoco_solver->sol->z[450];
  CPG_Dual.d25[14] = qoco_solver->sol->z[451];
  CPG_Dual.d25[15] = qoco_solver->sol->z[452];
  CPG_Dual.d25[16] = qoco_solver->sol->z[453];
  CPG_Dual.d25[17] = qoco_solver->sol->z[454];
  CPG_Dual.d25[18] = qoco_solver->sol->z[455];
  CPG_Dual.d25[19] = qoco_solver->sol->z[456];
  CPG_Dual.d25[20] = qoco_solver->sol->z[457];
  CPG_Dual.d25[21] = qoco_solver->sol->z[458];
  CPG_Dual.d25[22] = qoco_solver->sol->z[459];
  CPG_Dual.d25[23] = qoco_solver->sol->z[460];
  CPG_Dual.d25[24] = qoco_solver->sol->z[461];
  CPG_Dual.d25[25] = qoco_solver->sol->z[462];
  CPG_Dual.d25[26] = qoco_solver->sol->z[463];
  CPG_Dual.d25[27] = qoco_solver->sol->z[464];
  CPG_Dual.d25[28] = qoco_solver->sol->z[465];
  CPG_Dual.d25[29] = qoco_solver->sol->z[466];
  CPG_Dual.d25[30] = qoco_solver->sol->z[467];
  CPG_Dual.d25[31] = qoco_solver->sol->z[468];
  CPG_Dual.d25[32] = qoco_solver->sol->z[469];
  CPG_Dual.d25[33] = qoco_solver->sol->z[470];
  CPG_Dual.d25[34] = qoco_solver->sol->z[471];
  CPG_Dual.d25[35] = qoco_solver->sol->z[472];
}

// Retrieve solver info
void cpg_retrieve_info(){
  CPG_Info.obj_val = (qoco_solver->sol->obj + Canon_Params.d);
  CPG_Info.iter = qoco_solver->sol->iters;
  CPG_Info.status = qoco_solver->sol->status;
  CPG_Info.pri_res = qoco_solver->sol->pres;
  CPG_Info.dua_res = qoco_solver->sol->dres;
}

// Copy canonical parameters for preconditioning
void cpg_copy_P(){
  for (i=0; i<25; i++){
    Canon_Params_conditioning.P->x[i] = Canon_Params.P->x[i];
  }
}

void cpg_copy_c(){
  for (i=0; i<788; i++){
    Canon_Params_conditioning.c[i] = Canon_Params.c[i];
  }
}

void cpg_copy_A(){
  for (i=0; i<3893; i++){
    Canon_Params_conditioning.A->x[i] = Canon_Params.A->x[i];
  }
}

void cpg_copy_b(){
  for (i=0; i<389; i++){
    Canon_Params_conditioning.b[i] = Canon_Params.b[i];
  }
}

void cpg_copy_G(){
  for (i=0; i<1104; i++){
    Canon_Params_conditioning.G->x[i] = Canon_Params.G->x[i];
  }
}

void cpg_copy_h(){
  for (i=0; i<713; i++){
    Canon_Params_conditioning.h[i] = Canon_Params.h[i];
  }
}

void cpg_copy_all(){
  cpg_copy_P();
  cpg_copy_c();
  cpg_copy_A();
  cpg_copy_b();
  cpg_copy_G();
  cpg_copy_h();
}

// Solve via canonicalization, canonical solve, retrieval
void cpg_solve(){
  // Canonicalize if necessary
  if (Canon_Outdated.P) {
    cpg_canonicalize_P();
  }
  if (Canon_Outdated.c) {
    cpg_canonicalize_c();
  }
  if (Canon_Outdated.d) {
    cpg_canonicalize_d();
  }
  if (Canon_Outdated.A) {
    cpg_canonicalize_A();
  }
  if (Canon_Outdated.b) {
    cpg_canonicalize_b();
  }
  if (!qoco_solver ) {
    cpg_copy_all();
   QOCOCscMatrix* P = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   QOCOCscMatrix* A = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   QOCOCscMatrix* G = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   qoco_set_csc(P, 788, 788, Canon_Params.P->nnz, Canon_Params.P->x, Canon_Params.P->p, Canon_Params.P->i);
   qoco_set_csc(A, 389, 788, Canon_Params.A->nnz, Canon_Params.A->x, Canon_Params.A->p, Canon_Params.A->i);
   qoco_set_csc(G, 713, 788, Canon_Params.G->nnz, Canon_Params.G->x, Canon_Params.G->p, Canon_Params.G->i);
   QOCOSettings* qoco_settings = (QOCOSettings*)malloc(sizeof(QOCOSettings));
   set_default_settings(qoco_settings);
   qoco_solver = (QOCOSolver*)malloc(sizeof(QOCOSolver));
   qoco_setup(qoco_solver, 788, 713, 389, P, Canon_Params.c, A, Canon_Params.b, G, Canon_Params.h, 473, 25, (int *) &qoco_q, qoco_settings);
  }
  if (Canon_Outdated.c) {
    update_vector_data(qoco_solver, Canon_Params.c, NULL, NULL);
  }
  if (Canon_Outdated.P) {
    update_matrix_data(qoco_solver, Canon_Params.P->x, NULL, NULL);
  }
  if (Canon_Outdated.b) {
    update_vector_data(qoco_solver, NULL, Canon_Params.b, NULL);
  }
  if (Canon_Outdated.A) {
    update_matrix_data(qoco_solver, NULL, Canon_Params.A->x, NULL);
  }
  qoco_solver->settings->max_iters = Canon_Settings.max_iters;
  qoco_solver->settings->bisect_iters = Canon_Settings.bisect_iters;
  qoco_solver->settings->ruiz_iters = Canon_Settings.ruiz_iters;
  qoco_solver->settings->iter_ref_iters = Canon_Settings.iter_ref_iters;
  qoco_solver->settings->kkt_static_reg = Canon_Settings.kkt_static_reg;
  qoco_solver->settings->kkt_dynamic_reg = Canon_Settings.kkt_dynamic_reg;
  qoco_solver->settings->abstol = Canon_Settings.abstol;
  qoco_solver->settings->reltol = Canon_Settings.reltol;
  qoco_solver->settings->abstol_inacc = Canon_Settings.abstol_inacc;
  qoco_solver->settings->reltol_inacc = Canon_Settings.reltol_inacc;
  qoco_solver->settings->verbose = Canon_Settings.verbose;
  // Solve with QOCO
  qoco_solve(qoco_solver);
  // Retrieve results
  cpg_retrieve_prim();
  cpg_retrieve_dual();
  cpg_retrieve_info();
  // Reset flags for outdated canonical parameters
  Canon_Outdated.P = 0;
  Canon_Outdated.c = 0;
  Canon_Outdated.d = 0;
  Canon_Outdated.A = 0;
  Canon_Outdated.b = 0;
}

// Update solver settings
void cpg_set_solver_default_settings(){
  Canon_Settings.max_iters = 200;
  Canon_Settings.bisect_iters = 5;
  Canon_Settings.ruiz_iters = 0;
  Canon_Settings.iter_ref_iters = 1;
  Canon_Settings.kkt_static_reg = 1e-8;
  Canon_Settings.kkt_dynamic_reg = 1e-8;
  Canon_Settings.abstol = 1e-7;
  Canon_Settings.reltol = 1e-7;
  Canon_Settings.abstol_inacc = 1e-5;
  Canon_Settings.reltol_inacc = 1e-5;
  Canon_Settings.verbose = 0;
}

void cpg_set_solver_max_iters(cpg_int max_iters_new){
  Canon_Settings.max_iters = max_iters_new;
}

void cpg_set_solver_bisect_iters(cpg_int bisect_iters_new){
  Canon_Settings.bisect_iters = bisect_iters_new;
}

void cpg_set_solver_ruiz_iters(cpg_int ruiz_iters_new){
  Canon_Settings.ruiz_iters = ruiz_iters_new;
}

void cpg_set_solver_iter_ref_iters(cpg_int iter_ref_iters_new){
  Canon_Settings.iter_ref_iters = iter_ref_iters_new;
}

void cpg_set_solver_kkt_static_reg(cpg_float kkt_static_reg_new){
  Canon_Settings.kkt_static_reg = kkt_static_reg_new;
}

void cpg_set_solver_kkt_dynamic_reg(cpg_float kkt_dynamic_reg_new){
  Canon_Settings.kkt_dynamic_reg = kkt_dynamic_reg_new;
}

void cpg_set_solver_abstol(cpg_float abstol_new){
  Canon_Settings.abstol = abstol_new;
}

void cpg_set_solver_reltol(cpg_float reltol_new){
  Canon_Settings.reltol = reltol_new;
}

void cpg_set_solver_abstol_inacc(cpg_float abstol_inacc_new){
  Canon_Settings.abstol_inacc = abstol_inacc_new;
}

void cpg_set_solver_reltol_inacc(cpg_float reltol_inacc_new){
  Canon_Settings.reltol_inacc = reltol_inacc_new;
}

void cpg_set_solver_verbose(cpg_int verbose_new){
  Canon_Settings.verbose = verbose_new;
}
